on: 
  push:
    branches: 
      - main
name: Deploy theme to Prod
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - run: npm install --legacy-peer-deps
      - run: npm run build
      - name: Remove files that shouldn't be deployed
        run: rm -rf node_modules .git .github .gitignore package.json package-lock.json .env
      - name: SFTP-Deploy-Action
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: 'new-2026'
          server: 'new-2026.speedernet.com'
          port: '22'
          ssh_private_key: ${{ secrets.DEPLOY_KEY_PROD }}
          local_path: './*'
          remote_path: '/home/public_html/wp-content/themes/speedernet'
          sftp_only: true